name: Linting JavaScript files

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/*/src/**/*.ts'
      - 'eslint.config.js'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run build -w @w0s/shadow-append-css
      - run: npm run build -w @w0s/writing-mode
      - run: npm run js-lint
