name: writing-mode

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/writing-mode/src/**/*.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test -w '@w0s/writing-mode'
